### ISSUE TITLE
An error in GWAS_QC king 

### ISSUE THREAD

**Issue by changebio** [cumc/xqtl-pipeline#185]
Yu Liu met an error when using GWAS_QC and let me have a try with this pipeline. I got the following error. I think plink2 is not properly installed in bioinfo.sif. @gaow @hsun3163 
<img width="1522" alt="Screen Shot 2022-03-04 at 4 01 32 PM" src="https://user-images.githubusercontent.com/10182773/156840918-8c3f7bf7-9a5b-4175-a10d-2ddbdf7606b2.png">

**Comment by hsun3163** [comment]
This error is due to `module load singularity` was not ran in the bash.
There are three ways to solve it:
1. Run  `module load singularity` every time after logged in.
2. add  `module load singularity` to the .bashrc
3. Use the csg.yml in our repo and use `-c csg.yml -q csg` to submit the job, which will load singularity automatically

**Comment by changebio** [comment]
Thanks @hsun3163 . Let me forward your comment to Yu.
