### ISSUE TITLE
Using gff3 in generating star index

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#95]
Since our default annotation file is in gff3, our pipeline shall accomodate that.
According to 
`https://groups.google.com/g/rna-star/c/yl6JRltAuG4/m/bbuKHQM4AgAJ`

Using gff3 directly seems to be more complicated than what was implemented.

According to people from the star_group, 
>The GFF->GTF conversion uses these Parent relationships to add both transcript_id and gene_id to each exon line - so this is always the safest way to go.

They recommends converting the gff files beforehand. But someone in that discussion threads also seems to find a way to use gff3 directly.
 
Will investigate further.

**Comment by gaow** [comment]
Moving discussion to https://github.com/cumc/brain-xqtl-analysis/discussions/6 

@hsun3163 at this point let's stick to this gff3 file and convert it to gtf for use.

**Comment by yyeel** [comment]
First I would assume both gff3 and gtf provided by ENSEMBL version 103 should be the same 
 
I would actually add both gff3 and gtf into the annotation documentation, since that doc is for the whole ADSP use, not just for xQTL project. We are using gff format for other softwares. Therefore I would suggest we could make it more specific if that's helpful (like xQTL workgroup, use gtf for STARR analyses). 

How does that sound?

**Comment by gaow** [comment]
Thanks @yyeel good point -- let's do it as you suggest.
